### ISSUE TITLE
Cannot run gremlin.sh on ARM machine

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph-docker#123]
Note that the `./bin/gremlin.sh` inside the Docker image won't work for ARM machines due to the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, /tmp/libjansi-64-8999118035290383984.so: /tmp/libjansi-64-8999118035290383984.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
```

I am not sure why this is the case but running the server alone inside the Docker image is fine. I am able to download the zip file from https://github.com/JanusGraph/janusgraph/releases and use the local gremlin console to connect to the server (running in Docker). I am using openjdk version "1.8.0_275".

Seems the error message comes from a dependency of TinkerPop: https://github.com/fusesource/jansi/issues/207 but somehow it only fails to work in the Docker environment. Maybe it's due to the base environment that the Docker image uses.

_Originally posted by @li-boxuan in https://github.com/JanusGraph/janusgraph-docker/issues/92#issuecomment-1371780227_

**Comment by li-boxuan** [comment]
Need to remove https://github.com/JanusGraph/janusgraph/pull/3451#discussion_r1062382323 once this is fixed.

**Comment by jekramer** [comment]
This might be fixed with the recent bump to tinkerpop 3.6.2 that's already in the janusgraph master branch. I was getting the above UnsatisfiedLinkError trying to running gremlin console on my ARM laptop. 

I found [this commit](https://github.com/apache/tinkerpop/commit/4453649d68079e30a6c65651d21bf1a9c39e8c66) that seemed to indicate newest tinkerpop version would help. Tried running gremlin console locally from the artifacts from https://github.com/JanusGraph/janusgraph/actions/runs/4084297870 and was able to connect without the jansi error

**Comment by adubkov** [comment]
I can confirm - it does work when compiled and build image from tinkerpop repo.

**Comment by sruehl** [comment]
I'm getting the same error now with
```yaml
  janusgraph:
    image: docker.io/janusgraph/janusgraph:0.6.2
    container_name: janusgraph-default
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.
    volumes:
      - "janusgraph-default-data:/var/lib/janusgraph"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"

```
but only after I added a init script `initschema.groovy` to it. Before it booted just fine.

```log
janusgraph-default    | /usr/local/bin/load-initdb.sh: running /docker-entrypoint-initdb.d/initschema.groovy
janusgraph-default    | Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, /tmp/libjansi-64-6740405528050669019.so: /tmp/libjansi-64-6740405528050669019.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
janusgraph-default    | 	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
janusgraph-default    | 	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
janusgraph-default    | 	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
janusgraph-default    | 	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
janusgraph-default    | 	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
janusgraph-default    | 	at java.lang.Class.forName0(Native Method)
janusgraph-default    | 	at java.lang.Class.forName(Class.java:348)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64)
janusgraph-default    | 	at java.security.AccessController.doPrivileged(Native Method)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
janusgraph-default    | 	at org.apache.tinkerpop.gremlin.console.Colorizer.installAnsi(Colorizer.groovy:32)
janusgraph-default    | 	at org.apache.tinkerpop.gremlin.console.Colorizer$installAnsi.call(Unknown Source)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
janusgraph-default    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
janusgraph-default    | 	at org.apache.tinkerpop.gremlin.console.Console.<clinit>(Console.groovy:61)

```

**Comment by sruehl** [comment]
as a note: using latest in the compose doesn't help for me here:
```
❯ docker pull docker.io/janusgraph/janusgraph:latest
latest: Pulling from janusgraph/janusgraph
Digest: sha256:4dee07ac617210f8e803ac4ac0e06003785d39844280601d8fa9d63feb722778
Status: Image is up to date for janusgraph/janusgraph:latest
docker.io/janusgraph/janusgraph:latest

```

**Comment by sruehl** [comment]
Update: using `janusgraph/janusgraph:1.0.0-rc2` fixed that issue for me

**Comment by sruehl** [comment]
@li-boxuan I verified your exact issue (unless I missed some instructions) and it seems to work fine now with `1.0.0-rc2`:
```
❯ docker run -it janusgraph/janusgraph:1.0.0-rc2 /bin/bash

janusgraph@06c529036cae:/opt/janusgraph$ ./bin/gremlin.sh 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/janusgraph/lib/groovy-2.5.15-indy.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Feb 27, 2023 1:13:18 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/janusgraph/lib/log4j-slf4j-impl-2.20.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/janusgraph/lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
plugin activated: tinkerpop.server
plugin activated: tinkerpop.tinkergraph
13:13:20 INFO  org.apache.tinkerpop.gremlin.hadoop.jsr223.HadoopGremlinPlugin.getCustomizers - HADOOP_GREMLIN_LIBS is set to: /opt/janusgraph/lib
13:13:20 WARN  org.apache.hadoop.util.NativeCodeLoader.<clinit> - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.spark
plugin activated: tinkerpop.utilities
plugin activated: janusgraph.imports
gremlin> 

```
Maybe you can check it on your end too.

**Comment by li-boxuan** [comment]
@sruehl  Yes it's working, thanks for verifying!
