### ISSUE TITLE
500 Internal Server Error from janusgraph container

### ISSUE THREAD

**Issue by mkaisercross** [JanusGraph/janusgraph-docker#2]
I first run ./build-images.sh which works fine. 

Then I run 
docker-compose -f docker-compose-cassandra-es.yml up

I am getting the following 

```
jce-janusgraph   | 29285 [gremlin-server-exec-2] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 500 Internal Server Error and No such property: g for class: Script3

jce-janusgraph   | groovy.lang.MissingPropertyException: No such property: g for class: Script3

jce-janusgraph   | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)

jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)

jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)

jce-janusgraph   | 	at Script3.run(Script3.groovy:1)

jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:843)

jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:548)

jce-janusgraph   | 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)

jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:120)

jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:290)

jce-janusgraph   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

jce-janusgraph   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

jce-janusgraph   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

jce-janusgraph   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

jce-janusgraph   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

jce-janusgraph   | 	at java.lang.Thread.run(Thread.java:748)
```

When I try connecting from the gremlin console I get:

```
jce-janusgraph   | 29285 [gremlin-server-exec-2] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 500 Internal Server Error and No such property: g for class: Script3
jce-janusgraph   | groovy.lang.MissingPropertyException: No such property: g for class: Script3
jce-janusgraph   | at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
jce-janusgraph   | at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
jce-janusgraph   | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
jce-janusgraph   | at Script3.run(Script3.groovy:1)
jce-janusgraph   | at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:843)
jce-janusgraph   | at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:548)
jce-janusgraph   | at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
jce-janusgraph   | at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:120)
jce-janusgraph   | at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda-bash(GremlinExecutor.java:290)
jce-janusgraph   | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jce-janusgraph   | at java.util.concurrent.Executors.call(Executors.java:511)
jce-janusgraph   | at java.util.concurrent.FutureTask.run(FutureTask.javajce-janusgraph   | at java.util.concurrent.FutureTask.run(FutureTask.javajce-janusgraph   | at java.util.concurrent.FutureTask.rt java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
jce-janusgraph   | at java.lang.Thread.run(Thread.java:748)

```

I'll attach the full docker-compose output in a file.
[janusgraph-docker-compose-output.txt](https://github.com/JanusGraph/janusgraph-docker/files/2499736/janusgraph-docker-compose-output.txt)

## System Info
MacOS 10.13.1 
Docker CE Version 18.06.1-ce-mac73 (26764)

**Comment by pbaumer** [comment]
@nvizo were you ever able to resolve the above issue?

**Comment by FlorianHockmann** [comment]
Closed for inactivity. If this is still a problem with the current version of the image, then please create a new issue.
